title: <center>Anush Kumar</center> # your name (or website title) here
logo: "/images/new_dp_square.png?cropResize=50,50" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  <br>
  <center>
  <a href="https://anushl9o5.github.io/research_projects"><b>Research Projects</b></a> | <a href="https://anushl9o5.github.io/mini_projects"><b>Mini Projects</b></a>
  <br><br>
  <font size="-1"><i>
  Computer Vision <br>
  Robotics <br>
  Photography
  </i></font>
  <br><br>
  <a href="https://www.linkedin.com/in/anushl9o5/"><font size="-2"><b>LinkedIn</b></font></a> <a   href="https://drive.google.com/open?id=17P-SHknO9DTasOTai7lzgQy32eEpmB49"><font size="-2"><b> | Resume</b></font></a>
  <a href="https://www.instagram.com/_anushkumar/"><font size="-2"><b> | Instagram</b></font></a>
  </center>
  
theme: jekyll-theme-minimal
google_analytics: UA-142866422-1 # your Google Analytics tracking ID here
