title: Anush Kumar # your name (or website title) here
logo: "/images/cropped.jpg?cropResize=50,50" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Project Assistant - Video Analytics Lab, IISc 
  <br><br>
  Computer Vision | Robotics | Aritifical Intelligence | Embedded Systems
  <br><br>
  Amateur Photographer
  <br><br>
  <a href="https://www.linkedin.com/in/anushl9o5/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-142866422-1 # your Google Analytics tracking ID here
